baseURL = "https://huanglins.cn"
languageCode = "zn-cn"
title = "huanglins的个人博客"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "golang常用库"
	url = "/tool/"
	weight = 4

  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 5
  

[params]
    since = 2019
    author = "huanglins"                           # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "科技永无止境。"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = "蜀ICP备19030879号-2"
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "2016-huanglins"
    Email   = "huanglins@foxmail.com"

