baseURL                   = "https://huanglins.cn"
builddrafts                = false
languageCode               = "zh-cn"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "我的学习测试"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "关于"
    weight                 = -110
    identifier             = "about"
    url                    = "about/"  

  [[menu.main]]
    name                   = "golang常用库"
	weight                 = -100
	identifier             = "tool"
	url                    = "tool/"

 

[params]
  #faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/hl.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "huanglins"
  description              = ["热爱技术","热爱生活","面向未来" ]   
  #welcome_head             = "你好，欢迎"
  #welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "2006年1月2日 "
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "1261190152@qq.com"
  github                   = "https://github.com/2016-Lin/"
  
  
  # analytics
  #googleAnalytics          = "your-google-analytic-id"
    
    